# Generated by Django 5.1.1 on 2025-09-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_chapter_cost_chapter_is_premium_novel_free_chapters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='cost',
        ),
        migrations.AddField(
            model_name='novel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
